mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls



urlpatterns = [
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
] + debug_toolbar_urls()

polls/urls.py
from django.urls import path

from . import views

app_name ="polls"

urlpatterns = [
    #path("", views.IndiceVista.as_view(), name="indice"),
    path("", views.indice_vista, name="indice"),
    path("nueva_encuesta/", views.CrearPregunta.as_view(), name="crear_pregunta"),
    path("mapa/", views.mapa, name="mapa"),
    path("mapa2/", views.mapa2, name="mapa2"),
    path("mapa3/", views.mapa3, name="mapa3"),
    path("<int:pk>/", views.DetallesVista.as_view(), name="detalles"),
    path("<int:pk>/resultados/", views.ResultadosVista.as_view(), name="resultados"),
    path("<int:pregunta_id>/votacion/", views.votacion, name="votacion")
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin

# Create your models here.

class Pregunta(models.Model):
    texto_pregunta= models.CharField(max_length=200)
    fecha_publicacion= models.DateTimeField("date published")
    fecha_votacion = models.DateTimeField("date votacion", null=True, blank=True)
    
    @admin.display(
        boolean=True,
        ordering="fecha_publicacion",
        description="Publicado recientemente?",
    )
    def publicado_recientemente(self):
        fecha_actual = timezone.now()
        return fecha_actual - datetime.timedelta(days=1) <= self.fecha_publicacion <= fecha_actual

    def __str__(self):
        return self.texto_pregunta

class Opcion (models.Model):
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    texto_opcion= models.CharField(max_length=200)
    votos = models.IntegerField(default=0)
    
    def __str__(self):
        return self.texto_opcion
    

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.http import Http404
from django.db.models import F
from django.views import generic
from django.utils import timezone
from django.db.models import Sum, Value
from django.db.models.functions import Coalesce

from .models import Pregunta, Opcion

import json


def top_encuestas(min=3):
    mas_votadas = Pregunta.objects.filter(
    fecha_publicacion__lte=timezone.now()
    ).annotate(
        total_votos=Coalesce(Sum('opcion__votos'), Value(0))
    ).order_by('-total_votos')[:min]


    votadas_reciente = Pregunta.objects.order_by('-fecha_votacion')[:min]
    context = {
        #'ultimas_preguntas': ultimas_preguntas,
        'mas_votadas': mas_votadas,
        'votadas_reciente': votadas_reciente, 
    }

    return context

def indice_vista(request):
    ultimas_preguntas = Pregunta.objects.filter(
        fecha_publicacion__lte=timezone.now()
    ).order_by('-fecha_publicacion')
    context = top_encuestas()

    context["ultimas_preguntas"] = ultimas_preguntas


    return render(request, 'polls/index.html', context)

def mapa3(request):
    context = top_encuestas()
    return render(request, 'polls/mapa3.html', context)

def mapa2(request):
    context = top_encuestas()
    return render(request, 'polls/mapa2.html', context)

def mapa(request):
    with open("polls/static/polls/alcaldias.geojson", 'r', encoding='utf-8') as f:
        geojson_data = json.load(f)
    context = top_encuestas()
    context["geojson_data"] = geojson_data
    return render(request, 'polls/mapa.html', context)


class CrearPregunta(generic.CreateView):
    model= Pregunta
    fields = ["texto_pregunta", "fecha_publicacion"]
    template_name = "polls/crear_pregunta.html"


class DetallesVista(generic.DetailView):
    model= Pregunta
    template_name= "polls/detalles.html"

    def get_queryset(self):
        """
        Excluye cualquier pregunta que aún no se publique
        """
        return Pregunta.objects.filter(fecha_publicacion__lte=timezone.now())

class ResultadosVista(generic.DetailView):
    model = Pregunta
    template_name = "polls/resultados.html"

def votacion( request, pregunta_id):
    """
    Actualiza los votos, en la base de datos, de la opción seleccionada para la pregunta indicada,
    y redirige a la página de resultados. 
    Si el usario no seleccionada una opción, vuelve a renderizar la página.
    """
    pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
    try:
        pk = request.POST["opcion"]
        opcion_seleccionada= pregunta.opcion_set.get(pk= pk)
    except (KeyError, Opcion.DoesNotExist):
        context= {
            "pregunta": pregunta,
            "error_message": "No seleccionaste una opción"
        }
        return render(request, "polls/detalles.html", context )
    else:
        opcion_seleccionada.votos =  F("votos") + 1 
        opcion_seleccionada.save()
        pregunta.fecha_votacion = timezone.now()
        pregunta.save()
        return HttpResponseRedirect(reverse("polls:resultados", args=(pregunta_id,)))

polls/templates/polls/crear_pregunta.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">


<body>
    <div class="encabezado">
        <div class="logos">
            <img src="{% static 'polls/images/logo1.png' %}" alt="Logo Empresa" class="logo">
            <div class="titulo">Info Encuestas</div>
            <img src="{% static 'polls/images/logo2.png' %}" alt="Logo Institución" class="logo">
        </div>
        <div class="menu">
            <a href="{% url 'polls:indice' %}">Inicio</a>
            <a href="{% url 'polls:crear_pregunta' %}">Hacer encuesta</a>
            <a href="{% url 'polls:mapa' %}">Mapa</a>
            
        </div>
    </div>


    <!-- Contenido -->
    <div class="contenido_simple">
        <form method="post">
            {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save">
        </form>
    </div>
</body>

polls/templates/polls/crear_pregunta_f.html
<form >
    <div class="container">
      <h1>Registro de encuesta</h1>
      <p>Por favor complete la siguiente información.</p>
      <hr>
  
      <label for="pregunta"><b>Pregunta</b></label>
      <input type="text" placeholder="¿Qué quiere preguntar?" name="pregunta" id="pregunta" required>
  
      <label for="op1"><b>Opción 1</b></label>
      <input type="text" placeholder="Escriba la opción" name="op1" id="op1" required>
  
      <label for="op2"><b>Opción 2</b></label>
      <input type="text" placeholder="Escriba la opción" name="op2" id="op2" required>

      <label for="op3"><b>Opción 3</b></label>
      <input type="text" placeholder="Escriba la opción" name="op3" id="op3" required>
      
      <hr>
  
      <button type="submit" class="registerbtn">Guardar</button>
    </div>
    
</form>

polls/templates/polls/detalles.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">


<body>
    <div class="encabezado">
        <div class="logos">
            <img src="{% static 'polls/images/logo1.png' %}" alt="Logo Empresa" class="logo">
            <div class="titulo">Info Encuestas</div>
            <img src="{% static 'polls/images/logo2.png' %}" alt="Logo Institución" class="logo">
        </div>
        <div class="menu">
            <a href="{% url 'polls:indice' %}">Inicio</a>
            <a href="{% url 'polls:crear_pregunta' %}">Hacer encuesta</a>
            <a href="{% url 'polls:mapa' %}">Mapa</a>
        </div>
    </div>


    <!-- Contenido -->
    <div class="contenido_simple">
        <form action="{% url 'polls:votacion' pregunta.id %}" method="post">
            {% csrf_token %}
            <fieldset>
                <h1 class="titulo_centrado">{{ pregunta.texto_pregunta }}</h1>
                <p><strong>Seleccione una opción</strong></p>
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                {% for opcion in pregunta.opcion_set.all %}
                    <input type="radio" name="opcion" id="opcion{{ forloop.counter }}" value="{{ opcion.id }}">
                    <label for="opcion{{ forloop.counter }}">   {{ opcion.texto_opcion }}</label><br>
                    <p></p>
                {% endfor %}
                <p></p>
            
            <input type="submit" value="Votar">
            </fieldset>
        </form>
    </div>
</body>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">


<body>
    <div class="header">
        <!-- Logo de la empresa a la izquierda -->
        <img src="{% static 'polls/images/logo_infotec.png' %}" alt="Logo Empresa" class="logo">

        <!-- Nombre de la página al centro /home/esca/Proyectos/example/tutorial/polls/static/polls/images/background.png-->
        <div class="page-title">Info Encuestas</div>

        <!-- Logo de la institución a la derecha -->
        <img src="{% static 'polls/images/logo_infotec.png' %}" alt="Logo Institución" class="logo">
    </div>

    <!-- Menú de opciones -->
    <div class="header">
        <div class="menu">
            <a href="{% url 'polls:indice' %}">Inicio</a>
            <a href="{% url 'polls:indice' %}">Encuestas</a>
            <a href="{% url 'polls:indice' %}">Mapa</a>
        </div>
    </div>

    <!-- Contenido de la página -->
    <div class="content">
        {% if ultimas_preguntas %}
        <h1>Bienvenido a la página de encuestas</h1>
        <p> El listado de preguntas se muestra a continuación, seleccione una pregunta para dar su voto. </p>
        <ul>
        {% for pregunta in ultimas_preguntas %}
            <li><a href="{% url 'polls:detalles' pregunta.id %}">{{ pregunta.texto_pregunta }}</a></li>
        {% endfor %}
        </ul>
        {% else %}
            <p>Lo sentimos. Aún no hay preguntas.</p>
        {% endif %}
    </div>
</body>
</html>

polls/templates/polls/mapa.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>



<body>
    <div class="encabezado">
        <div class="logos">
            <img src="{% static 'polls/images/logo1.png' %}" alt="Logo Empresa" class="logo">
            <div class="titulo">Info Encuestas</div>
            <img src="{% static 'polls/images/logo2.png' %}" alt="Logo Institución" class="logo">
        </div>
        <div class="menu">
            <a href="{% url 'polls:indice' %}">Inicio</a>
            <a href="{% url 'polls:crear_pregunta' %}">Hacer encuesta</a>
            <a href="{% url 'polls:mapa' %}">Mapa</a>
            
        </div>
    </div>

    
    <div class="contenido">
        <div class="barra_lateral">
            <!-- Contenido de barra_lateral -->
            <p> <strong>Encuestas más votadas </strong> </p>
            {% if mas_votadas %}
            {% for pregunta in mas_votadas %}
                <li><a href="{% url 'polls:resultados' pregunta.id %}">{{ pregunta.texto_pregunta }}</a></li>
                <p></p>
            {% endfor %}
            </ul >
            {% else %}
                <p>Lo sentimos. Aún no hay preguntas.</p>
            {% endif %}

            <p> <strong>Encuestas votadas recientemente </strong> </p>
            
            {% if mas_votadas %}
            {% for pregunta in votadas_reciente %}
                <li><a href="{% url 'polls:resultados' pregunta.id %}">{{ pregunta.texto_pregunta }}</a></li>
                <p></p>
            {% endfor %}
            </ul>
            {% else %}
                <p>Lo sentimos. Aún no hay preguntas.</p>
            {% endif %}
        </div>
        <!-- Contenido -->
        <div class="contenido_principal">
            <legend><h1 class="titulo_centrado">MAPA WEB</h1></legend>
            <div id="map"></div>
            <script>
                // Mapa Leafletjs
                var openstreetmap = L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
                    maxZoom: 19,
                    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
                    })

                var satelite = L.tileLayer("http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}",{
                    maxZoom:18,
                })

                var map = L.map('map', {
                    center: [19.19, -99.14609],
                    zoom: 10,
                    layers: [openstreetmap]
                });

                function popup(feature, layer) { 
                if (feature.properties && feature.properties.NOMGEO) 
                { 
                layer.bindPopup(feature.properties.NOMGEO); 
                } 
                }

                
                var geojsonData = L.geoJSON({{ geojson_data|safe }},{onEachFeature: popup}).addTo(map);

                var alcaldias = L.layerGroup([geojsonData]);
                var mapas_base = {
                    "OpenStreetMap": openstreetmap,
                    "Google Satelite": satelite,
                };

                var capas = {
                    "Alcaldías": alcaldias
                };

                var layerControl = L.control.layers(mapas_base, capas).addTo(map);
                
           
              </script>
        </div>

    </div>
</body>

polls/templates/polls/mapa2.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
<script src="https://code.jquery.com/jquery-3.6.3.js"></script>


<body>
    <div class="encabezado">
        <div class="logos">
            <img src="{% static 'polls/images/logo1.png' %}" alt="Logo Empresa" class="logo">
            <div class="titulo">Info Encuestas</div>
            <img src="{% static 'polls/images/logo2.png' %}" alt="Logo Institución" class="logo">
        </div>
        <div class="menu">
            <a href="{% url 'polls:indice' %}">Inicio</a>
            <a href="{% url 'polls:crear_pregunta' %}">Hacer encuesta</a>
            <a href="{% url 'polls:mapa' %}">Mapa</a>
            
        </div>
    </div>

    
    <div class="contenido">
        <div class="barra_lateral">
            <!-- Contenido de barra_lateral -->
            <p> <strong>Encuestas más votadas </strong> </p>
            {% if mas_votadas %}
            {% for pregunta in mas_votadas %}
                <li><a href="{% url 'polls:resultados' pregunta.id %}">{{ pregunta.texto_pregunta }}</a></li>
                <p></p>
            {% endfor %}
            </ul >
            {% else %}
                <p>Lo sentimos. Aún no hay preguntas.</p>
            {% endif %}

            <p> <strong>Encuestas votadas recientemente </strong> </p>
            
            {% if mas_votadas %}
            {% for pregunta in votadas_reciente %}
                <li><a href="{% url 'polls:resultados' pregunta.id %}">{{ pregunta.texto_pregunta }}</a></li>
                <p></p>
            {% endfor %}
            </ul>
            {% else %}
                <p>Lo sentimos. Aún no hay preguntas.</p>
            {% endif %}
        </div>
        <!-- Contenido -->
        <div class="contenido_principal">
            <legend><h1 class="titulo_centrado">MAPA WEB</h1></legend>
            <div id="map"></div>
            <script>
                // Mapa Leafletjs
                var openstreetmap = L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
                    maxZoom: 19,
                    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
                    })

                var satelite = L.tileLayer("http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}",{
                    maxZoom:18,
                })

                var map = L.map('map', {
                    center: [19.19, -99.14609],
                    zoom: 10,
                    layers: [openstreetmap]
                });

                function popup(feature, layer) { 
                if (feature.properties && feature.properties.NOMGEO) 
                { 
                layer.bindPopup(feature.properties.NOMGEO); 
                } 
                }
                
                var geojsonData =  L.geoJson(null, {
                        onEachFeature: popup
                    });
                $.getJSON("{% static 'polls/alcaldias.geojson' %}", function(alcaldias) {
                    geojsonData.addData(alcaldias);
                    geojsonData.addTo(map)
                });

                /*
                    // OTRA FORMA DE HACER ES USANDO fetch en lugar de $.getJSON
                    fetch("{% static 'polls/alcaldias.geojson' %}")
                        .then(response => response.json())
                        .then(data => {
                            geojsonData.addData(alcaldias);
                            geojsonData.addTo(map)
                        });
                */

                var alcaldias = L.layerGroup([geojsonData]);
                var mapas_base = {
                    "OpenStreetMap": openstreetmap,
                    "Google Satelite": satelite,
                };

                var capas = {
                    "Alcaldías": alcaldias
                };

                var layerControl = L.control.layers(mapas_base, capas).addTo(map);
            
              </script>
        </div>

    </div>
</body>

polls/templates/polls/mapa3.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
<script type="text/javascript" src="{% static 'polls/alcaldias.js' %}"></script>


<body>
    <div class="encabezado">
        <div class="logos">
            <img src="{% static 'polls/images/logo1.png' %}" alt="Logo Empresa" class="logo">
            <div class="titulo">Info Encuestas</div>
            <img src="{% static 'polls/images/logo2.png' %}" alt="Logo Institución" class="logo">
        </div>
        <div class="menu">
            <a href="{% url 'polls:indice' %}">Inicio</a>
            <a href="{% url 'polls:crear_pregunta' %}">Hacer encuesta</a>
            <a href="{% url 'polls:mapa' %}">Mapa</a>
            
        </div>
    </div>

    
    <div class="contenido">
        <div class="barra_lateral">
            <!-- Contenido de barra_lateral -->
            <p> <strong>Encuestas más votadas </strong> </p>
            {% if mas_votadas %}
            {% for pregunta in mas_votadas %}
                <li><a href="{% url 'polls:resultados' pregunta.id %}">{{ pregunta.texto_pregunta }}</a></li>
                <p></p>
            {% endfor %}
            </ul >
            {% else %}
                <p>Lo sentimos. Aún no hay preguntas.</p>
            {% endif %}

            <p> <strong>Encuestas votadas recientemente </strong> </p>
            
            {% if mas_votadas %}
            {% for pregunta in votadas_reciente %}
                <li><a href="{% url 'polls:resultados' pregunta.id %}">{{ pregunta.texto_pregunta }}</a></li>
                <p></p>
            {% endfor %}
            </ul>
            {% else %}
                <p>Lo sentimos. Aún no hay preguntas.</p>
            {% endif %}
        </div>
        <!-- Contenido -->
        <div class="contenido_principal">
            <legend><h1 class="titulo_centrado">MAPA WEB</h1></legend>
            <div id="map"></div>
            <script>
                // Mapa Leafletjs
                var openstreetmap = L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
                    maxZoom: 19,
                    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
                    })

                var satelite = L.tileLayer("http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}",{
                    maxZoom:18,
                })

                var map = L.map('map', {
                    center: [19.19, -99.14609],
                    zoom: 10,
                    layers: [openstreetmap]
                });

                function popup(feature, layer) { 
                if (feature.properties && feature.properties.NOMGEO) 
                { 
                layer.bindPopup(feature.properties.NOMGEO); 
                } 
                }

                
                var geojsonData = L.geoJSON(geojson,{onEachFeature: popup}).addTo(map);

                var alcaldias = L.layerGroup([geojsonData]);
                var mapas_base = {
                    "OpenStreetMap": openstreetmap,
                    "Google Satelite": satelite,
                };

                var capas = {
                    "Alcaldías": alcaldias
                };

                var layerControl = L.control.layers(mapas_base, capas).addTo(map);
                
           
              </script>
        </div>

    </div>
</body>

polls/templates/polls/resultados.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">


<body>
    <div class="encabezado">
        <div class="logos">
            <img src="{% static 'polls/images/logo1.png' %}" alt="Logo Empresa" class="logo">
            <div class="titulo">Info Encuestas</div>
            <img src="{% static 'polls/images/logo2.png' %}" alt="Logo Institución" class="logo">
        </div>
        <div class="menu">
            <a href="{% url 'polls:indice' %}">Inicio</a>
            <a href="{% url 'polls:crear_pregunta' %}">Hacer encuesta</a>
            <a href="{% url 'polls:mapa' %}">Mapa</a>
            
        </div>
    </div>


    <!-- Contenido -->
    <div class="contenido_simple">
        <h1 class="titulo_centrado" >{{ pregunta.texto_pregunta }}</h1>
        <h2 class="titulo_centrado">Resumen de la votación:</h2>
        
        <table>
            <thead>
                <tr>
                    <th>Opción</th>
                    <th>Votos</th>
                </tr>
            </thead>
            <tbody>
                {% for opcion in pregunta.opcion_set.all %}
                <tr>
                    <td>{{ opcion.texto_opcion }}</td>
                    <td>{{ opcion.votos }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <p></p>
        <a href="{% url 'polls:detalles' pregunta.id %}"style="display: block; text-align: center; margin: 0 auto;"> ¿Quieres votar de nuevo?</a>
    </div>
</body>